name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - doesnotexist
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - doesnotexist

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: 🧶 Set up Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🛠️ Build monorepo (via Turbo or workspaces)
        run: |
          echo "Printing all environments"
          printenv
          echo "NEXT_PUBLIC_NEXTAUTH_SECRET: $NEXT_PUBLIC_NEXTAUTH_SECRET"
          echo "NEXT_PUBLIC_NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
          echo "NEXT_PUBLIC_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}"
          yarn build
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.ENV_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.ENV_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.ENV_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.ENV_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.ENV_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.ENV_FIREBASE_MEASUREMENT_ID }}
          NEXT_PUBLIC_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}
          NEXT_PUBLIC_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          CALENDSO_ENCRYPTION_KEY: ${{ secrets.CALENDSO_ENCRYPTION_KEY }}
          NEXT_PUBLIC_API_V2_URL: ${{ secrets.NEXT_PUBLIC_API_V2_URL }}
          CALCOM_LICENSE_KEY: ""
          CAL_SIGNATURE_TOKEN: ""
          CALCOM_PRIVATE_API_ROUTE: "https://goblin.cal.com"
          DATABASE_URL: "postgresql://postgres:@localhost:5450/calendso"
          DATABASE_DIRECT_URL: "postgresql://postgres:@localhost:5450/calendso"
          INSIGHTS_DATABASE_URL: ""
          PRISMA_GENERATE_DATAPROXY: ""
          NEXT_PUBLIC_WEBAPP_URL: "http://localhost:3000"
          NEXT_PUBLIC_WEBSITE_URL: "http://localhost:3000"
          NEXT_PUBLIC_CONSOLE_URL: "http://localhost:3004"
          NEXT_PUBLIC_EMBED_LIB_URL: "http://localhost:3000/embed/embed.js"
          SAML_DATABASE_URL: ""
          SAML_ADMINS: ""
          NEXT_PUBLIC_HOSTED_CAL_FEATURES: ""
          SAML_CLIENT_SECRET_VERIFIER: ""
          PGSSLMODE: ""
          ALLOWED_HOSTNAMES: '"cal.com","cal.dev","cal-staging.com","cal.community","cal.local:3000","localhost:3000"'
          RESERVED_SUBDOMAINS: '"app","auth","docs","design","console","go","status","api","saml","www","matrix","developer","cal","my","team","support","security","blog","learn","admin"'
          NEXTAUTH_COOKIE_DOMAIN: ""
          CALCOM_TELEMETRY_DISABLED: ""
          CRON_API_KEY: "0cc0e6c35519bba620c9360cfe3e68d0"
          CRON_ENABLE_APP_SYNC: "false"
          NEXT_PUBLIC_INTERCOM_APP_ID: ""
          INTERCOM_SECRET: ""
          NEXT_PUBLIC_POSTHOG_KEY: ""
          NEXT_PUBLIC_POSTHOG_HOST: ""
          PLAIN_API_KEY: ""
          PLAIN_API_URL: "https://api.plain.com/v1"
          PLAIN_HMAC_SECRET_KEY: ""
          NEXT_PUBLIC_PLAIN_CHAT_ID: ""
          PLAIN_CHAT_HMAC_SECRET_KEY: ""
          NEXT_PUBLIC_PLAIN_CHAT_EXCLUDED_PATHS: ""
          NEXT_PUBLIC_ZENDESK_KEY: ""
          NEXT_PUBLIC_HELPSCOUT_KEY: ""
          NEXT_PUBLIC_FRESHCHAT_TOKEN: ""
          NEXT_PUBLIC_FRESHCHAT_HOST: ""
          GOOGLE_LOGIN_ENABLED: "false"
          GOOGLE_API_CREDENTIALS: ""
          GOOGLE_WEBHOOK_TOKEN: ""
          GOOGLE_WEBHOOK_URL: ""
          SEND_FEEDBACK_EMAIL: ""
          SENDGRID_API_KEY: ""
          SENDGRID_EMAIL: ""
          NEXT_PUBLIC_SENDGRID_SENDER_NAME: ""
          NEXT_PUBLIC_SENTRY_DSN: ""
          SENTRY_DEBUG: ""
          SENTRY_DISABLE_CLIENT_SOURCE_MAPS: ""
          SENTRY_DISABLE_SERVER_SOURCE_MAPS: ""
          SENTRY_MAX_SPANS: ""
          SENTRY_TRACES_SAMPLE_RATE: ""
          NEXT_PUBLIC_FORMBRICKS_HOST_URL: "https://app.formbricks.com"
          NEXT_PUBLIC_FORMBRICKS_ENVIRONMENT_ID: ""
          FORMBRICKS_FEEDBACK_SURVEY_ID: ""
          AVATARAPI_USERNAME: ""
          AVATARAPI_PASSWORD: ""
          TWILIO_SID: ""
          TWILIO_TOKEN: ""
          TWILIO_MESSAGING_SID: ""
          TWILIO_PHONE_NUMBER: ""
          TWILIO_WHATSAPP_PHONE_NUMBER: ""
          NEXT_PUBLIC_SENDER_ID: ""
          TWILIO_VERIFY_SID: ""
          NEXT_PUBLIC_IS_E2E: ""
          NEXT_PUBLIC_STRIPE_PRO_PLAN_PRICE: ""
          NEXT_PUBLIC_STRIPE_PREMIUM_PLAN_PRICE: ""
          NEXT_PUBLIC_IS_PREMIUM_NEW_PLAN: "0"
          NEXT_PUBLIC_STRIPE_PREMIUM_NEW_PLAN_PRICE: ""
          STRIPE_TEAM_MONTHLY_PRICE_ID: ""
          STRIPE_TEAM_PRODUCT_ID: ""
          STRIPE_ORG_MONTHLY_PRICE_ID: ""
          STRIPE_ORG_PRODUCT_ID: ""
          STRIPE_WEBHOOK_SECRET: ""
          STRIPE_WEBHOOK_SECRET_APPS: ""
          STRIPE_PRIVATE_KEY: ""
          STRIPE_CLIENT_ID: ""
          API_KEY_PREFIX: "cal_"
          EMAIL_FROM: "notifications@yourselfhostedcal.com"
          EMAIL_FROM_NAME: "Cal.com"
          EMAIL_SERVER_HOST: "localhost"
          EMAIL_SERVER_PORT: "1025"
          E2E_TEST_MAILHOG_ENABLED: ""
          NEXT_PUBLIC_CLOUDFLARE_SITEKEY: ""
          NEXT_PUBLIC_CLOUDFLARE_USE_TURNSTILE_IN_BOOKER: ""
          CLOUDFLARE_TURNSTILE_SECRET: ""
          NEXT_PUBLIC_TEAM_IMPERSONATION: "false"
          CLOSECOM_CLIENT_ID: ""
          CLOSECOM_CLIENT_SECRET: ""
          SENDGRID_SYNC_API_KEY: ""
          NEXT_PUBLIC_APP_NAME: "Cal.com"
          NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS: "help@cal.com"
          NEXT_PUBLIC_COMPANY_NAME: "Cal.com, Inc."
          NEXT_PUBLIC_DISABLE_SIGNUP: ""
          CSP_POLICY: ""
          EDGE_CONFIG: ""
          NEXT_PUBLIC_MINUTES_TO_BOOK: "5"
          NEXT_PUBLIC_BOOKER_NUMBER_OF_DAYS_TO_LOAD: "0"
          NEXT_PUBLIC_AVAILABILITY_SCHEDULE_INTERVAL: ""
          ORGANIZATIONS_ENABLED: ""
          NEXT_PUBLIC_ORGANIZATIONS_MIN_SELF_SERVE_SEATS: "30"
          NEXT_PUBLIC_ORGANIZATIONS_SELF_SERVE_PRICE_NEW: "37"
          ORGANIZATIONS_AUTOLINK: ""
          PROJECT_ID_VERCEL: ""
          TEAM_ID_VERCEL: ""
          AUTH_BEARER_TOKEN_VERCEL: ""
          LOCAL_TESTING_DOMAIN_VERCEL: ""
          E2E_TEST_APPLE_CALENDAR_EMAIL: ""
          E2E_TEST_APPLE_CALENDAR_PASSWORD: ""
          E2E_TEST_CALCOM_QA_EMAIL: "qa@example.com"
          E2E_TEST_CALCOM_QA_PASSWORD: "password"
          E2E_TEST_CALCOM_QA_GCAL_CREDENTIALS: ""
          E2E_TEST_CALCOM_GCAL_KEYS: ""
          CALCOM_CREDENTIAL_SYNC_SECRET: ""
          CALCOM_CREDENTIAL_SYNC_HEADER_NAME: "calcom-credential-sync-secret"
          CALCOM_CREDENTIAL_SYNC_ENDPOINT: ""
          CALCOM_APP_CREDENTIAL_ENCRYPTION_KEY: ""
          E2E_TEST_SAML_ADMIN_EMAIL: ""
          E2E_TEST_SAML_ADMIN_PASSWORD: ""
          E2E_TEST_OIDC_CLIENT_ID: ""
          E2E_TEST_OIDC_CLIENT_SECRET: ""
          E2E_TEST_OIDC_PROVIDER_DOMAIN: ""
          E2E_TEST_OIDC_USER_EMAIL: ""
          E2E_TEST_OIDC_USER_PASSWORD: ""
          SENTRY_DISABLE_SERVER_WEBPACK_PLUGIN: "1"
          TASKER_ENABLE_WEBHOOKS: "0"
          TASKER_ENABLE_EMAILS: "0"
          UNKEY_ROOT_KEY: ""
          RETELL_AI_KEY: ""
          HUDDLE01_API_TOKEN: ""
          BLACKLISTED_GUEST_EMAILS: ""
          NEXT_PUBLIC_VAPID_PUBLIC_KEY: ""
          VAPID_PRIVATE_KEY: ""
          NEXT_PUBLIC_MINTLIFY_CHAT_API_KEY: ""
          NEXT_PUBLIC_CHAT_API_URL: ""
          NEXT_PUBLIC_DOCS_URL: ""
          NEXT_PUBLIC_WEBSITE_PRIVACY_POLICY_URL: ""
          NEXT_PUBLIC_WEBSITE_TERMS_URL: ""
          NEXT_PUBLIC_LOGGER_LEVEL: ""
          CAL_VIDEO_BUCKET_NAME: ""
          CAL_VIDEO_BUCKET_REGION: ""
          CAL_VIDEO_ASSUME_ROLE_ARN: ""
      - name: 🔐 Get ID token for Azure auth
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: 🚀 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        id: builddeploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MOSS_0210CC310 }}
          action: "upload"
          # Point to the built output folder inside your monorepo
          app_location: "apps/web"                         # where your Next.js app lives
          output_location: "apps/web/out"                  # where Next.js exports static site (after `next export`)
          api_location: ""                                 # optional
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
